leon/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostDeleteView,
    PostListView,
    PostCreateView,
    PostUpdateView,
)
app_name = 'leon'

urlpatterns = [
    #local : http://127.0.0.1:8000/
    path('',PostListView.as_view(), name='post_list'),
    path('new/', PostCreateView.as_view(), name = 'post_create'),
    path('<int:id>' , PostDetailView.as_view(), name='post_detail'),
    path('<int:id>/update/', PostUpdateView.as_view(), name='post_update'),
    path('<int:id>/delete/', PostDeleteView.as_view(), name='post_delete'),
]

leongram/urls.py
from django.urls import path , include
from django.contrib import admin
from django.contrib.auth import views as auth_views 
from users import views as user_views 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('leon.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leon/models.py
from time import timezone
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from datetime import datetime

# image = Profile Photo
# Bio = caption

class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null =True)
    caption = models.TextField()
    saved = models.BooleanField(default=False)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')
    created_period = models.DateTimeField(default=datetime.now)
    
    def __str__(self):
        return self.caption
    @property
    def published(self):
        created_dates = self.created_date.replace(tzinfo=None)
        Now = datetime.now()
        Now = Now.replace(microsecond=0)
        time_difference = Now - created_dates
        if time_difference.days == 0:
            if int(time_difference.seconds/3600) == 0:
                self.published_date = str(int(time_difference.seconds/60)) + " minutes ago"
            else:
                self.published_date = str(int(time_difference.seconds/3600)) + " hours ago"
        else:
            self.published_date = str(int(time_difference.days)) + " days ago"   
        self.save()
        return self.published_date  

users/models.py
from django.db import models

# Create your models here.

leon/forms.py
from django import forms 
from .models import Post
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field 
from crispy_forms.bootstrap import (
    PrependedText, PrependedAppendedText, FormActions
)

class PostForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('Post', 'Post', css_class='btn-primary'))

    class Meta:
        model = Post 
        fields = [
            'image',
            'caption'
        ]

users/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm 

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

leon/views.py
from datetime import timezone
from django.contrib.auth.models import User 
from django.shortcuts import render, get_object_or_404
from leon.forms import PostForm
from django.utils import timezone
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.urls import reverse 
from .models import Post 
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    RedirectView,
)

class PostListView(ListView):
    template_name = 'pages/postlist.html'
    queryset = Post.objects.all().filter(created_period__lte=timezone.now()).order_by('-created_period')
    context_object_name = 'posts'

class PostCreateView(CreateView):
    template_name = 'pages/post_create.html'
    form_class = PostForm
    queryset=Post.objects.all()
    success_url = '/'
    
    def form_valid(self, form):
        print(form.cleaned_data)
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    
class PostDetailView(DetailView):
    template_name = 'pages/post_detail.html'
    queryset = Post.objects.all().filter(created_period__lte=timezone.now())    
    def get_object(self):
        id = self.kwargs.get('id')
        return get_object_or_404(Post, id=id)
    
    
class PostUpdateView(UpdateView):
    template_name = 'pages/create.html'
    form_class = PostForm 

    def get_object(self):
     id_ = self.kwargs.get("id")
     return get_object_or_404(Post, id=id)

    def form_valid(self, form):
            form.instance.author = self.request.user 
            return super().form_valid(form) 

class PostDeleteView(DeleteView):
    template_name = 'pages/delete.html'

    def get_object(self):
        id_=self.kwargs.get("id")
        return get_object_or_404(Post, id=id)

    def get_success_url(self):
        return reverse('pages:post_list')  
      
 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm
# Create your views here.

def register(request):
    if request.method == 'POST':
        print("This shit is working bro.")
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            print(username,"This shit is working")
            messages.success(request, f'Account created for {username} successfully!')
            return redirect('/')
    else:
        #If there is no a post request just send an empty form
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

#The decoratior add functionality to the function is this case the login required functionality
@login_required
def profile(request):
    return render(request, 'users/profile.html')

"""
Messages is django.

message.debug
message.info
message.success
message.warning
message.error 

"""

leon/templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- <link rel="stylesheet" href="static/css/insta.css"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'leon/leon.css' %}">
    <title>{% block title%}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="navigation">
            <div class="instalogo">
                <a href=""><i class="fab fa-instagram"></i> </a>
                <a class="vl"></a>
                <a href="/">Dante's instagram</a>
                <br><br>
            </div>
            <div class="search_bar">
                <input type="text" placeholder="Search">
                <a href="search"><i class="fas fa-search"></i></a>
            </div>
            <div class="contact_icons">
                <a href="{% url 'leon:post_create'%}"> {{ PostCreateView }}<i class="fa fa-plus" aria-hidden="true"></i></a>
                <a href=""><i class="far fa-compass"></i></a>
                {% if user.is_authenticated %}
                    <a href=""> <i class="far fa-heart"></i> </a>
                    <a href=""> <i class="far fa-user"></i> </a>
                {% endif %}
            </div>
        </div>
    </header>
    <div class="container content-container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {%endblock%}

    </div>
    <script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
  <script>
    // function updateText(btn, newCount){
    //     btn.text(newCount)
    // }
    $(".like-btn").click(function(e){
    e.preventDefault()
    var this_ = $(this)
    var likeUrl = this_.attr("data-href")
    var likeCount = parseInt(this_.attr("data-likes")) | 0
    var addLike = likeCount + 1 
    var removeLike = likeCount - 1 
    $.ajax({
        url: likeUrl,
        method: "get",
        data: {},
        success: function(data){
            console.log(data)
            var NewLikes;
            if (data.liked){
                $(".likes_count").text(addLike + " likes") 
                // add one like 
            } else {
                $(".likes_count").text(removeLike + " likes")


                // remove one like 
            }
        }, error: function(error){
            console.log(error)
            console.log("error")
        }
    })
})
</script>
<script>
    $(".follow_button").click(function(e){
        e.preventDefault() 
        var thiss_ = $(this)
        var follow_url = thiss_.attr("follow-href")
        var follow_count = parseInt(thiss_.attr("data-follow")) | 0 
        var addfollow = follow_count + 1 
        var removefollow = follow_count - 1
        if (follow_url){
            $.ajax({
                url: follow_url,
                method: "get",
                data: {},
                success: function(data){
                    console.log(data)
                    if (data.follow){
                        $(".number_of_followers").text(addfollow)
                        $(".follow_button").text("Following")
                    } else {
                        $(".number_of_followers").text(removefollow)
                        $(".follow_button").text("Follow")
                    }

                }, error: function(error){
                console.log(error)
                console.log("error")}

            })
        }

    })
    function updateText(btn, newCount){
        btn.text(newCount)
    }
    $(".like-btn").click(function(e){
    e.preventDefault()
    var this_ = $(this)
    var likeUrl = this_.attr("data-href")
    var likeCount = parseInt(this_.attr("data-likes"))
    .ajax({
        url: likeUrl,
        method: "get",
        data: {},
        success: function(data){
            console.log(data)
            var NewLikes;
            if (data.liked){
                var NewLikes = likeCount + 1
                updateText(this_, NewLikes)
                // add one like 
            } else {
                var NewLikes = likeCount - 1
                updateText(this_, NewLikes)
                // remove one like 
            }
        }, error: function(error){
            console.log(error)
            console.log("error")
        }
    })
})
</script>
</body>
</html>

leon/templates/pages/delete.html
{% extends 'pages/base.html' %}

{% block content %}

<form action="." method="POST">{% csrf_token %}
    <h2>Do you want to delete this post now ?</h2>
    <img class='post_image' src="{{ post.image.url }}" alt="">
    <p>{{ post.caption }}</p>
    <p> <input type='submit' value='Yes'/><a href="/">Cancel</a></p>
</form>

{% endblock %}

leon/templates/pages/details.html
{% extends 'pages/base.html' %}
{%block title%} Dantes Instagram {% endblock %}

{% block content %}
<div class="detail_card">
    <div class="detail_image">
        <img src="{{post.image.url }}" alt="">
    </div>
    <div class="post_detail_info">
        <div class="card_header">
            <div class="profile_image">
                
            </div>
            <div class="post_info">
                <div class="post_name"><a href="">{{ post.author }}</a></div>
                <div class="post_location">Panama</div>
            </div>
            <div class="post_options"><a href=""><i class="fas fa-ellipsis-h"></i></a></div>
        </div>

        <div class="detail_bottom">
            <div class="engage">
                <a href=""><i class="fas fa-heart"></i></a>
                <a href="{% url 'pages:post_detail' post.id %}"><i class="far fa-comment"></i></a>
                <a href=""><i class="far fa-share-square"></i></a>
                <a href="" class="fa-bookmarks"><i class="far fa-bookmark"></i></a>
            </div>
            <div class="likes">
                <a href="#">{{ post.likes.count }} likes</a>
            </div>
            <div class="time_posted">
                {{post.created_date | timesince}} ago
            </div>
            <div class="new_comment_section">
                <form action="">
                    <textarea name="" id="" class="text_comment_area" placeholder="Add a comment..." cols="30" rows="10"></textarea>
                    
                    <button type="submit">Post</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

leon/templates/pages/menu_modal.html
<div class="modal fade " id="menu_modal">
    <div class="model-dialog">
        <div class="model-content">
            <ul class='list-unstyled menu'>
                <li><a class="text-reset" href="">Edit</a></li>
                <li><a class="text-reset" href="">Details</a></li>
                <li><a class="text-reset" href="">Delete</a></li>
                <li><a class="text-reset" href="">Cancel</a></li>
              </ul>
        </div>
    </div>
</div>

leon/templates/pages/post_create.html
{% extends 'pages/base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="panel panel-default" style="width: 500px; margin:0 auto">
    <div class="panel-body">
        {% crispy form %} {% csrf_token %}
    </div>

</div>


{% endblock %}

leon/templates/pages/post_detail.html
{% extends 'pages/base.html' %} {% block content %}

<p>{{ post.author }}</p>
<img src="{{ post.image.url }}" height="640" alt="">
<p>{{post.caption}}</p>



{% endblock %}

leon/templates/pages/postlist.html
{% extends "pages/base.html" %} {% block content %} {% for post in posts %}
<div class="card">
    <div class="card_header">
        <div class="profile_image">
            <img src="{{ post.author.profile.profile_photo.url }}" alt="">
        </div>
        <div class="post_info">
            <div class="post_name"> {{post.author}}</div>
            <div class="post_location">Panama</div>
        </div>

        <div class="post_options"> <button data-toggle="modal" data-target="#menu_modal"><a ><i class="fas fa-ellipsis-h"></i></a></button></div>
    </div>
    <div class="modal" id="menu_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <ul class='list-unstyled menu'>
                    <li><a class="text-reset" href="{% url 'leon:post_update' post.id %}">Edit</a></li>
                    <li><a class="text-reset" href="{% url 'leon:post_delete' post.id %}">Delete</a></li>
                    <li><a class="text-reset" href="{% url 'leon:post_detail' post.id %}">Details</a></li>
                    <li><a class="text-reset close" data-dismiss="modal" href="">Cancel</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="post_image">
        {% if post.image %}
        <img src="{{ post.image.url }}" alt=""> {% endif %}
    </div>
    <div class="engage">
        <a href=""><i class="fa fa-heartbeat" aria-hidden="true"></i></a>
        <a href=""><i class="fa fa-comment" aria-hidden="true"></i></a>
        <a href=""><i class="fa fa-share-alt" aria-hidden="true"></i> </a>
        <a href=""><i class="fa fa-bookmark" aria-hidden="true"></i></a>
    </div>
    <div class="likes">
        <a href="#" class="likes_count">{{ post.likes.count }} likes</a>
    </div>
    <div class="caption">
        <a href="">
            <h3>{{post.author}}</h3>
        </a>
        <span> <p>{{post.caption}}</p></span>
    </div>
    <div class="time_posted">
        {{post.created_period | timesince }} ago
    </div>

</div>
{% include "pages/menu_modal.html" %} {% endfor %} {% endblock content %}

users/templates/users/login.html
{% extends 'pages/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock %}

users/templates/users/logout.html
{% extends 'pages/base.html' %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a class="ml-2" href="{% url 'login' %}">Login again</a>
        </small>
    </div>
    
{% endblock %}

users/templates/users/profile.html
{% extends 'pages/base.html' %}
{% block content %}
    <h2>{{ user.username }}</h2>
{% endblock %}

users/templates/users/register.html
{% extends 'pages/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Now</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock %}